// Package auth provides JWT token validation for WebSocket authentication.
package auth

import (
	"fmt"

	"github.com/golang-jwt/jwt/v5"
)

// Claims represents the JWT payload generated by the Laravel backend.
type Claims struct {
	Room string `json:"room"`
	Role string `json:"role"`
	Name string `json:"name"`
	jwt.RegisteredClaims
}

// ValidateToken parses and validates a JWT token string using HS256 with the given secret.
// Returns the parsed claims or an error if the token is invalid or expired.
func ValidateToken(tokenStr, secret string) (*Claims, error) {
	token, err := jwt.ParseWithClaims(tokenStr, &Claims{}, func(t *jwt.Token) (interface{}, error) {
		if _, ok := t.Method.(*jwt.SigningMethodHMAC); !ok {
			return nil, fmt.Errorf("unexpected signing method: %v", t.Header["alg"])
		}
		return []byte(secret), nil
	})
	if err != nil {
		return nil, fmt.Errorf("token validation failed: %w", err)
	}

	claims, ok := token.Claims.(*Claims)
	if !ok || !token.Valid {
		return nil, fmt.Errorf("invalid token claims")
	}

	return claims, nil
}
